// Code generated by abstraction-idl from abstraction-rights/rights.thrift. DO NOT EDIT.

// abstraction.rights.api: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

// applied, conflict and unknown carry the revision observed inside the
// conditional edit. applied and conflict carry the action's registration entry
// when one exists; a seeded or retired action has none. unknown means
// RetireAction named an action outside the catalogue. exhausted means the
// catalogue already holds 64 actions. invalid, exhausted, forbidden and
// unavailable carry no revision or entry. A stale expected revision always
// conflicts.
export interface ActionEdit {
  outcome: ActionEditOutcome;
  revision: string;
  current: CatalogEntry | null;
}

export type ActionEditOutcome = (typeof ActionEditOutcome)[keyof typeof ActionEditOutcome];
export declare const ActionEditOutcome: Readonly<{ Applied: "applied"; Conflict: "conflict"; Unknown: "unknown"; Invalid: "invalid"; Exhausted: "exhausted"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// Own application registration fields; registered uses the existing RFC3339
// time representation. Native App additionally carries identity.listen.Seen
// observation evidence.
export interface AppMetadata {
  id: string;
  name: string;
  rights: string[];
  registered: string;
}

/** General exact-rule authorization decision point with a bounded, registrable catalogue and persistence. Unknown, absent, unspecified, expired, failed and refused decisions never permit. Explicitly authorized operator configuration registers actions and grants/revokes exact rules; no serialized awake lease is introduced. */
export declare class AuthorizationClient {
  constructor(transport: FrameTransport);
  /** Evaluate the bound receiving account/program against an exact action/resource rule. This result is advisory to the caller; resource services query the decision point themselves. */
  decide(action: string, resource: string): Promise<Decision>;
  /** Evaluate a subject assertion only when the receiving peer is explicitly authorized as an enforcement point for this action/resource. Same account alone grants no relay authority. The designated enforcer is trusted to supply its actual bound subject. Nil or refusing enforcer policy yields forbidden before policy lookup. */
  decideFor(subject: Subject, action: string, resource: string): Promise<Decision>;
}

/** Explicitly authorized administration of the configured decision policy: catalogue registration and retirement, exact rules with expiry and provenance. Receiving same-account Program proof plus a trusted typed-peer operator callback is required; nil refuses. Policy denial is forbidden; callback/storage failure is unavailable. No caller credential, verified flag or provider path is accepted. Resource services remain the receiving enforcement points. Legacy bearer and awake lease behavior is separate. */
export declare class AuthorizationOperatorClient {
  constructor(transport: FrameTransport);
  /** Read bounded current rules and catalogue under explicit operator authorization. Every continuation rechecks authorization; no enumeration session is retained for disconnected/slow callers. */
  listPolicy(cursor: string, limit: bigint): Promise<PolicyPage>;
  /** Atomically compare the expected durable revision and set one exact permit/deny rule with no expiry and an empty reason. Revision is bounded to 128 UTF-8 bytes. Operator context and authority are checked again inside the atomic edit after lock waiting. The rule records the operator's established subject and the edit time. An unexpired rule with the same permit is a no-op that keeps its record. Uncatalogued actions and malformed targets are invalid; no resource permission is inferred from the operator request itself. */
  setRule(expectedRevision: string, rule: PolicyRule): Promise<PolicyEdit>;
  /** Atomically remove one exact rule if the revision matches. The next fresh decision observes successful revocation. A failed/uncertain reply claims no successful revocation; inspect current state before another intent. It does not cancel an existing connection-owned awake lease. */
  revokeRule(expectedRevision: string, subject: Subject, action: string, resource: string): Promise<PolicyEdit>;
  /** As SetRule, recording why and an expiry ttl_ms after the service's edit time. ttl_ms 0 sets no expiry; otherwise it is 1..31536000000. why is 0..256 UTF-8 bytes without control characters. A retained rule with the same permit, reason and expiry is a no-op; any other difference writes, including a new expiry. */
  setRuleFor(expectedRevision: string, rule: PolicyRule, ttlMs: bigint, why: string): Promise<PolicyEdit>;
  /** Read one exact rule with its provenance and expiry under operator authorization, rechecked after the read. */
  readRule(subject: Subject, action: string, resource: string): Promise<RuleRead>;
  /** Add an action named <owner>/<name> to the catalogue. owner is 1..64 bytes and name 1..63 bytes of lowercase ASCII letters, digits, '.', '_' and '-', each beginning with a letter or digit. Registering an action already in the catalogue applies without writing. A registration records the operator's established subject and the service time. Registration grants nothing: decisions on the action read not_granted until a rule exists. */
  registerAction(expectedRevision: string, action: string): Promise<ActionEdit>;
  /** Remove a registered action and every rule naming it. Retiring a seeded action is invalid. Retiring an action outside the catalogue is unknown. Decisions on a retired action read unknown_action. */
  retireAction(expectedRevision: string, action: string): Promise<ActionEdit>;
}

export declare const AuthorizationOperatorService: Readonly<{ wireName: "abstraction.rights/operator@1"; Client: typeof AuthorizationOperatorClient }>;

export declare const AuthorizationService: Readonly<{ wireName: "abstraction.rights/authorization@1"; Client: typeof AuthorizationClient }>;

// One registered catalogue action. Seeded actions have no entry. registered_by
// is the subject the rights service established for the registering party: the
// operator's receiving Program evidence, or the service's own account and
// executable for native registration. registered_at is the service's UTC time
// as RFC 3339 with milliseconds.
export interface CatalogEntry {
  action: string;
  registeredBy: Subject;
  registeredAt: string;
}

// A point-in-time policy decision. Only permitted allows an enforcement point
// to proceed. denied is an explicit exact deny; not_granted has no unexpired
// exact rule; unknown_action is outside the current catalogue. Evaluated
// permitted/denied/not_granted/unknown_action decisions carry an opaque
// revision observed with that decision. Errors carry none. No lease, token,
// cached permission lifetime or human consent is conveyed.
export interface Decision {
  outcome: DecisionOutcome;
  policyRevision: string;
}

export type DecisionOutcome = (typeof DecisionOutcome)[keyof typeof DecisionOutcome];
export declare const DecisionOutcome: Readonly<{ Permitted: "permitted"; Denied: "denied"; NotGranted: "not_granted"; UnknownAction: "unknown_action"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

// Own held-right fields; since uses existing RFC3339 time representation.
// Native Hold also carries Seen. The live Lease is connection-owned and cannot
// be recreated from these fields.
export interface HoldMetadata {
  app: string;
  name: string;
  right: string;
  why: string;
  since: string;
}

// Applied/conflict carry the revision and optional exact current rule observed
// inside the conditional edit; absent current means no exact rule. Other
// outcomes carry no revision/current. A stale expected revision always
// conflicts, including when the desired state happens to match. No-op edits at
// the matching revision preserve it without writing. A lost reply is uncertain:
// retrying the same expected revision cannot overwrite a later edit, and may
// conflict after a successful original change. Reconcile the returned current
// state or fresh history before choosing another edit. This is optimistic
// concurrency, not an exactly-once mutation journal.
export interface PolicyEdit {
  outcome: PolicyEditOutcome;
  revision: string;
  current: PolicyRule | null;
}

export type PolicyEditOutcome = (typeof PolicyEditOutcome)[keyof typeof PolicyEditOutcome];
export declare const PolicyEditOutcome: Readonly<{ Applied: "applied"; Conflict: "conflict"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// Latest-policy enumeration: 1..64 requested rules and at most 256 KiB encoded
// reply, including catalogue, cursor and indentation. Catalogue is the
// configured seed plus registered actions, sorted, bounded to 64 actions of 128
// bytes. Rules are every retained rule, including expired rules the next write
// removes; ReadRule reports expiry and provenance. Page carries the exact
// durable content revision. A noncomplete page has a nonempty next cursor.
// Refusals have empty revision/catalog/rules/next and complete=false. Cursors
// are at most 256 UTF-8 bytes, bind receiving account/program and host
// epoch/revision, and return gap after change/restart/scope mismatch. Restart
// from empty cursor. No immutable multipage snapshot or historical change
// replay is promised.
export interface PolicyPage {
  outcome: PolicyPageOutcome;
  revision: string;
  catalog: string[];
  rules: PolicyRule[];
  next: string;
  complete: boolean;
}

export type PolicyPageOutcome = (typeof PolicyPageOutcome)[keyof typeof PolicyPageOutcome];
export declare const PolicyPageOutcome: Readonly<{ Page: "page"; Gap: "gap"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// One exact policy rule. Subject is the administrative target, never caller
// proof. Account is 1..128 UTF-8 bytes; program is a normalized absolute path
// up to 4096 bytes; action is 1..128 bytes and belongs to the current
// catalogue; resource is 1..1024 bytes. All strings exclude control characters.
// permit=false is an explicit deny; revocation removes the exact rule and
// restores not_granted.
export interface PolicyRule {
  subject: Subject;
  action: string;
  resource: string;
  permit: boolean;
}

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// Existing rights request concepts. Secret/token/admin remain credential inputs
// checked by the service; request text never substitutes for native peer
// identity. This descriptor does not replace the existing handwritten line
// transport.
export interface Request {
  op: string;
  name: string;
  rights: string[];
  secret: string;
  token: string;
  right: string;
  why: string;
  app: string;
  admin: string;
}

// Own response fields projected without native Seen evidence. Any nonempty
// code/error is refusal, including unknown codes. This is a common descriptor,
// not a replacement legacy Response codec or generated service client.
export interface ResponseMetadata {
  code: string;
  error: string;
  secret: string;
  token: string;
  expires: string;
  app: AppMetadata | null;
  right: string;
  apps: AppMetadata[];
  holds: HoldMetadata[];
}

// found and expired carry the revision and the exact record. expired names a
// retained rule at or past its expiry; it decides nothing and the next policy
// write removes it. unknown carries the revision and no record. invalid,
// forbidden and unavailable carry neither.
export interface RuleRead {
  outcome: RuleReadOutcome;
  revision: string;
  record: RuleRecord | null;
}

export type RuleReadOutcome = (typeof RuleReadOutcome)[keyof typeof RuleReadOutcome];
export declare const RuleReadOutcome: Readonly<{ Found: "found"; Expired: "expired"; Unknown: "unknown"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// One exact rule with its provenance. set_by is the subject the rights service
// established for the party that set the rule: the operator's receiving Program
// evidence, or the service's own account and executable for native edits. The
// request never supplies it. set_at is the service's UTC edit time as RFC 3339
// with milliseconds. why is the operator's reason of 0..256 UTF-8 bytes without
// control characters. expires is empty for a rule without expiry, or the UTC
// instant, in the same format, from which the rule decides nothing.
export interface RuleRecord {
  rule: PolicyRule;
  setBy: Subject;
  setAt: string;
  why: string;
  expires: string;
}

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode" }>;

// Account identifier and normalized absolute executable path. This serialized
// subject is an assertion by an explicitly authorized enforcement point. It
// contains no proof or verified flag and cannot authorize its own use. Direct
// decisions derive their subject from native receiving Program evidence.
export interface Subject {
  account: string;
  program: string;
}

export declare function decode(data: Uint8Array): Request;

export declare function encode(v: Request): Uint8Array;

export declare const knownRights: readonly ["awake"];

export declare function newActionEdit(): ActionEdit;

export declare function newAppMetadata(): AppMetadata;

export declare function newCatalogEntry(): CatalogEntry;

export declare function newDecision(): Decision;

export declare function newHoldMetadata(): HoldMetadata;

export declare function newPolicyEdit(): PolicyEdit;

export declare function newPolicyPage(): PolicyPage;

export declare function newPolicyRule(): PolicyRule;

export declare function newRequest(): Request;

export declare function newResponseMetadata(): ResponseMetadata;

export declare function newRuleRead(): RuleRead;

export declare function newRuleRecord(): RuleRecord;

export declare function newSubject(): Subject;

export declare const operations: readonly ["register", "ask", "hold", "check", "apps", "grant", "revoke", "forget", "holds"];

export declare const refusalCodes: readonly ["internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "pending", "denied", "denied_permanently", "unsupported_hold", "platform_refused", "unknown_app", "unknown_right", "not_granted", "bad_secret", "bad_token"];

export declare const resourceActions: readonly ["abstraction.storage/content.read", "abstraction.storage/content.write", "abstraction.job/acceptance.submit", "abstraction.job/acceptance.cancel", "abstraction.config/user.replace", "abstraction.logging/history.read", "abstraction.model/lookup", "abstraction.router/inventory.read", "abstraction.router/route", "abstraction.storage/content.observe", "abstraction.storage/content.remove"];

export {};
