// Code generated by abstraction-idl from abstraction-rights/rights.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

export class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
export function num(out, n) { out.ascii(BigInt(n).toString()); }

export function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

export function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

export function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

export function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

export function encList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const DecisionOutcomeNames = ["permitted", "denied", "not_granted", "unknown_action", "invalid", "forbidden", "unavailable"];
export const DecisionOutcomeUnknown = "refuse";

export const PolicyPageOutcomeNames = ["page", "gap", "invalid", "forbidden", "unavailable"];
export const PolicyPageOutcomeUnknown = "refuse";

export const PolicyEditOutcomeNames = ["applied", "conflict", "invalid", "forbidden", "unavailable"];
export const PolicyEditOutcomeUnknown = "refuse";

export const operations = ["register", "ask", "hold", "check", "apps", "grant", "revoke", "forget", "holds"];

export const knownRights = ["awake"];

export const refusalCodes = ["internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "pending", "denied", "denied_permanently", "unsupported_hold", "platform_refused", "unknown_app", "unknown_right", "not_granted", "bad_secret", "bad_token"];

export const resourceActions = ["abstraction.storage/content.read"];

export function enc_request(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "op");
  out.ascii(": ");
  esc(out, v.op);
  if (v.name !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "name");
    out.ascii(": ");
    esc(out, v.name);
  }
  if (v.rights.length !== 0) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "rights");
    out.ascii(": ");
    strs(out, v.rights, depth + 1);
  }
  if (v.secret !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "secret");
    out.ascii(": ");
    esc(out, v.secret);
  }
  if (v.token !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "token");
    out.ascii(": ");
    esc(out, v.token);
  }
  if (v.right !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "right");
    out.ascii(": ");
    esc(out, v.right);
  }
  if (v.why !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "why");
    out.ascii(": ");
    esc(out, v.why);
  }
  if (v.app !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "app");
    out.ascii(": ");
    esc(out, v.app);
  }
  if (v.admin !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "admin");
    out.ascii(": ");
    esc(out, v.admin);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_appmetadata(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "name");
  out.ascii(": ");
  esc(out, v.name);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "rights");
  out.ascii(": ");
  strs(out, v.rights, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "registered");
  out.ascii(": ");
  esc(out, v.registered);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_holdmetadata(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "app");
  out.ascii(": ");
  esc(out, v.app);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "name");
  out.ascii(": ");
  esc(out, v.name);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "right");
  out.ascii(": ");
  esc(out, v.right);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "why");
  out.ascii(": ");
  esc(out, v.why);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "since");
  out.ascii(": ");
  esc(out, v.since);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_responsemetadata(out, v, depth) {
  out.byte(0x7b);
  let first = true;
  if (v.code !== "") {
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "code");
    out.ascii(": ");
    esc(out, v.code);
  }
  if (v.error !== "") {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "error");
    out.ascii(": ");
    esc(out, v.error);
  }
  if (v.secret !== "") {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "secret");
    out.ascii(": ");
    esc(out, v.secret);
  }
  if (v.token !== "") {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "token");
    out.ascii(": ");
    esc(out, v.token);
  }
  if (v.expires !== "") {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "expires");
    out.ascii(": ");
    esc(out, v.expires);
  }
  if (v.app !== undefined && v.app !== null) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "app");
    out.ascii(": ");
    enc_appmetadata(out, v.app, depth + 1);
  }
  if (v.right !== "") {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "right");
    out.ascii(": ");
    esc(out, v.right);
  }
  if (v.apps.length !== 0) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "apps");
    out.ascii(": ");
    encList(out, v.apps, depth + 1, enc_appmetadata);
  }
  if (v.holds.length !== 0) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "holds");
    out.ascii(": ");
    encList(out, v.holds, depth + 1, enc_holdmetadata);
  }
  if (!first) { out.byte(0x0a); pad(out, depth); }
  out.byte(0x7d);
}

export function enc_subject(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "account");
  out.ascii(": ");
  esc(out, v.account);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "program");
  out.ascii(": ");
  esc(out, v.program);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_decision(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "permitted" && v.outcome !== "denied" && v.outcome !== "not_granted" && v.outcome !== "unknown_action" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.policy_revision !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "policy_revision");
    out.ascii(": ");
    esc(out, v.policy_revision);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_policyrule(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "subject");
  out.ascii(": ");
  enc_subject(out, v.subject, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "action");
  out.ascii(": ");
  esc(out, v.action);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "permit");
  out.ascii(": ");
  out.ascii(v.permit ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_policypage(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "revision");
  out.ascii(": ");
  esc(out, v.revision);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "catalog");
  out.ascii(": ");
  strs(out, v.catalog, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "rules");
  out.ascii(": ");
  encList(out, v.rules, depth + 1, enc_policyrule);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "next");
  out.ascii(": ");
  esc(out, v.next);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "complete");
  out.ascii(": ");
  out.ascii(v.complete ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_policyedit(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "applied" && v.outcome !== "conflict" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "revision");
  out.ascii(": ");
  esc(out, v.revision);
  if (v.current !== undefined && v.current !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "current");
    out.ascii(": ");
    enc_policyrule(out, v.current, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationdecidearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "action");
  out.ascii(": ");
  esc(out, v.action);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationdecideforarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "subject");
  out.ascii(": ");
  enc_subject(out, v.subject, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "action");
  out.ascii(": ");
  esc(out, v.action);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationoperatorlistpolicyarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "limit");
  out.ascii(": ");
  num(out, v.limit);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationoperatorsetrulearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "expected_revision");
  out.ascii(": ");
  esc(out, v.expected_revision);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "rule");
  out.ascii(": ");
  enc_policyrule(out, v.rule, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationoperatorrevokerulearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "expected_revision");
  out.ascii(": ");
  esc(out, v.expected_revision);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "subject");
  out.ascii(": ");
  enc_subject(out, v.subject, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "action");
  out.ascii(": ");
  esc(out, v.action);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceframe(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaservicereply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceerror(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationdecideresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_decision(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationdecideforresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_decision(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationoperatorlistpolicyresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_policypage(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationoperatorsetruleresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_policyedit(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaauthorizationoperatorrevokeruleresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_policyedit(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  enc_request(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function decodeList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

export function newRequest() {
  return { op: "", name: "", rights: [], secret: "", token: "", right: "", why: "", app: "", admin: "" };
}

export function newAppMetadata() {
  return { id: "", name: "", rights: [], registered: "" };
}

export function newHoldMetadata() {
  return { app: "", name: "", right: "", why: "", since: "" };
}

export function newResponseMetadata() {
  return { code: "", error: "", secret: "", token: "", expires: "", app: null, right: "", apps: [], holds: [] };
}

export function newSubject() {
  return { account: "", program: "" };
}

export function newDecision() {
  return { outcome: "", policy_revision: "" };
}

export function newPolicyRule() {
  return { subject: newSubject(), action: "", resource: "", permit: false };
}

export function newPolicyPage() {
  return { outcome: "", revision: "", catalog: [], rules: [], next: "", complete: false };
}

export function newPolicyEdit() {
  return { outcome: "", revision: "", current: null };
}

export function newOAAuthorizationDecideArguments() {
  return { action: "", resource: "" };
}

export function newOAAuthorizationDecideForArguments() {
  return { subject: newSubject(), action: "", resource: "" };
}

export function newOAAuthorizationOperatorListPolicyArguments() {
  return { cursor: "", limit: 0n };
}

export function newOAAuthorizationOperatorSetRuleArguments() {
  return { expected_revision: "", rule: newPolicyRule() };
}

export function newOAAuthorizationOperatorRevokeRuleArguments() {
  return { expected_revision: "", subject: newSubject(), action: "", resource: "" };
}

export function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

export function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

export function newOAServiceError() {
  return { code: "", message: "" };
}

export function newOAAuthorizationDecideResult() {
  return { value: newDecision() };
}

export function newOAAuthorizationDecideForResult() {
  return { value: newDecision() };
}

export function newOAAuthorizationOperatorListPolicyResult() {
  return { value: newPolicyPage() };
}

export function newOAAuthorizationOperatorSetRuleResult() {
  return { value: newPolicyEdit() };
}

export function newOAAuthorizationOperatorRevokeRuleResult() {
  return { value: newPolicyEdit() };
}

function decode_request(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "op") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.op = r.string();
      } else if (key === "name") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.name = r.string();
      } else if (key === "rights") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.rights = r.strList();
      } else if (key === "secret") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.secret = r.string();
      } else if (key === "token") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.token = r.string();
      } else if (key === "right") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.right = r.string();
      } else if (key === "why") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.why = r.string();
      } else if (key === "app") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.app = r.string();
      } else if (key === "admin") {
        if (seen & 256) throw r.refuse("duplicate_field");
        seen |= 256;
        v.admin = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_appmetadata(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAppMetadata();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else if (key === "name") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.name = r.string();
      } else if (key === "rights") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.rights = r.strList();
      } else if (key === "registered") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.registered = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_holdmetadata(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHoldMetadata();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "app") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.app = r.string();
      } else if (key === "name") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.name = r.string();
      } else if (key === "right") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.right = r.string();
      } else if (key === "why") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.why = r.string();
      } else if (key === "since") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.since = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function decode_responsemetadata(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResponseMetadata();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "error") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.error = r.string();
      } else if (key === "secret") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.secret = r.string();
      } else if (key === "token") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.token = r.string();
      } else if (key === "expires") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.expires = r.string();
      } else if (key === "app") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.app = decode_appmetadata(r);
      } else if (key === "right") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.right = r.string();
      } else if (key === "apps") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.apps = decodeList(r, decode_appmetadata);
      } else if (key === "holds") {
        if (seen & 256) throw r.refuse("duplicate_field");
        seen |= 256;
        v.holds = decodeList(r, decode_holdmetadata);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

function decode_subject(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newSubject();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "account") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.account = r.string();
      } else if (key === "program") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.program = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_decision(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newDecision();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "policy_revision") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.policy_revision = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "permitted" && v.outcome !== "denied" && v.outcome !== "not_granted" && v.outcome !== "unknown_action" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_policyrule(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newPolicyRule();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "subject") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.subject = decode_subject(r);
      } else if (key === "action") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.action = r.string();
      } else if (key === "resource") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.resource = r.string();
      } else if (key === "permit") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.permit = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_policypage(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newPolicyPage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "revision") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.revision = r.string();
      } else if (key === "catalog") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.catalog = r.strList();
      } else if (key === "rules") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.rules = decodeList(r, decode_policyrule);
      } else if (key === "next") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.next = r.string();
      } else if (key === "complete") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.complete = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 63) >>> 0) !== 63) throw r.refuse("missing_field");
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_policyedit(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newPolicyEdit();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "revision") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.revision = r.string();
      } else if (key === "current") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.current = decode_policyrule(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
    if (v.outcome !== "applied" && v.outcome !== "conflict" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_oaauthorizationdecidearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationDecideArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "action") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.action = r.string();
      } else if (key === "resource") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.resource = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationdecideforarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationDecideForArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "subject") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.subject = decode_subject(r);
      } else if (key === "action") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.action = r.string();
      } else if (key === "resource") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.resource = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationoperatorlistpolicyarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationOperatorListPolicyArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "limit") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.limit = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationoperatorsetrulearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationOperatorSetRuleArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "expected_revision") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.expected_revision = r.string();
      } else if (key === "rule") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.rule = decode_policyrule(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationoperatorrevokerulearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationOperatorRevokeRuleArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "expected_revision") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.expected_revision = r.string();
      } else if (key === "subject") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.subject = decode_subject(r);
      } else if (key === "action") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.action = r.string();
      } else if (key === "resource") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.resource = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceframe(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaservicereply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceerror(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationdecideresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationDecideResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_decision(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationdecideforresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationDecideForResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_decision(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationoperatorlistpolicyresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationOperatorListPolicyResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_policypage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationoperatorsetruleresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationOperatorSetRuleResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_policyedit(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oaauthorizationoperatorrevokeruleresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAAuthorizationOperatorRevokeRuleResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_policyedit(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = decode_request(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
export const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

export function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["Request"] = [["op","string","never"],["name","string","absent"],["rights","list<string>","zero"],["secret","string","absent"],["token","string","absent"],["right","string","absent"],["why","string","absent"],["app","string","absent"],["admin","string","absent"],];
_serviceRecords["AppMetadata"] = [["id","string","never"],["name","string","never"],["rights","list<string>","never"],["registered","string","never"],];
_serviceRecords["HoldMetadata"] = [["app","string","never"],["name","string","never"],["right","string","never"],["why","string","never"],["since","string","never"],];
_serviceRecords["ResponseMetadata"] = [["code","string","absent"],["error","string","absent"],["secret","string","absent"],["token","string","absent"],["expires","string","absent"],["app","AppMetadata","absent"],["right","string","absent"],["apps","list<AppMetadata>","zero"],["holds","list<HoldMetadata>","zero"],];
_serviceRecords["Subject"] = [["account","string","never"],["program","string","never"],];
_serviceRecords["Decision"] = [["outcome","string","never"],["policy_revision","string","absent"],];
_serviceRecords["PolicyRule"] = [["subject","Subject","never"],["action","string","never"],["resource","string","never"],["permit","bool","never"],];
_serviceRecords["PolicyPage"] = [["outcome","string","never"],["revision","string","never"],["catalog","list<string>","never"],["rules","list<PolicyRule>","never"],["next","string","never"],["complete","bool","never"],];
_serviceRecords["PolicyEdit"] = [["outcome","string","never"],["revision","string","never"],["current","PolicyRule","absent"],];
_serviceRecords["OAAuthorizationDecideArguments"] = [["action","string","never"],["resource","string","never"],];
_serviceRecords["OAAuthorizationDecideForArguments"] = [["subject","Subject","never"],["action","string","never"],["resource","string","never"],];
_serviceRecords["OAAuthorizationOperatorListPolicyArguments"] = [["cursor","string","never"],["limit","i64","never"],];
_serviceRecords["OAAuthorizationOperatorSetRuleArguments"] = [["expected_revision","string","never"],["rule","PolicyRule","never"],];
_serviceRecords["OAAuthorizationOperatorRevokeRuleArguments"] = [["expected_revision","string","never"],["subject","Subject","never"],["action","string","never"],["resource","string","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OAAuthorizationDecideResult"] = [["value","Decision","never"],];
_serviceRecords["OAAuthorizationDecideForResult"] = [["value","Decision","never"],];
_serviceRecords["OAAuthorizationOperatorListPolicyResult"] = [["value","PolicyPage","never"],];
_serviceRecords["OAAuthorizationOperatorSetRuleResult"] = [["value","PolicyEdit","never"],];
_serviceRecords["OAAuthorizationOperatorRevokeRuleResult"] = [["value","PolicyEdit","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(enc_oaserviceframe, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(decode_oaservicereply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(decode_oaserviceerror, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class AuthorizationClient {
  constructor(transport) { this._transport = transport; }
  async Decide(arg0,arg1) {
    const args = newOAAuthorizationDecideArguments();
    args["action"] = arg0;
    args["resource"] = arg1;
    _serviceCheck("OAAuthorizationDecideArguments", args);
    const payload = _serviceEncode(enc_oaauthorizationdecidearguments, args, 1);
    _serviceDecode(decode_oaauthorizationdecidearguments, payload, 1);
    const request = _serviceRequest("abstraction.rights/authorization@1", "Decide", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.rights/authorization@1", "Decide");
    const result = _serviceDecode(decode_oaauthorizationdecideresult, reply, 1);
    return result.value;
  }
  async DecideFor(arg0,arg1,arg2) {
    const args = newOAAuthorizationDecideForArguments();
    args["subject"] = arg0;
    args["action"] = arg1;
    args["resource"] = arg2;
    _serviceCheck("OAAuthorizationDecideForArguments", args);
    const payload = _serviceEncode(enc_oaauthorizationdecideforarguments, args, 1);
    _serviceDecode(decode_oaauthorizationdecideforarguments, payload, 1);
    const request = _serviceRequest("abstraction.rights/authorization@1", "DecideFor", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.rights/authorization@1", "DecideFor");
    const result = _serviceDecode(decode_oaauthorizationdecideforresult, reply, 1);
    return result.value;
  }
}
export const AuthorizationService = Object.freeze({wireName:"abstraction.rights/authorization@1",Client:AuthorizationClient});

export class AuthorizationOperatorClient {
  constructor(transport) { this._transport = transport; }
  async ListPolicy(arg0,arg1) {
    const args = newOAAuthorizationOperatorListPolicyArguments();
    args["cursor"] = arg0;
    args["limit"] = arg1;
    _serviceCheck("OAAuthorizationOperatorListPolicyArguments", args);
    const payload = _serviceEncode(enc_oaauthorizationoperatorlistpolicyarguments, args, 1);
    _serviceDecode(decode_oaauthorizationoperatorlistpolicyarguments, payload, 1);
    const request = _serviceRequest("abstraction.rights/operator@1", "ListPolicy", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.rights/operator@1", "ListPolicy");
    const result = _serviceDecode(decode_oaauthorizationoperatorlistpolicyresult, reply, 1);
    return result.value;
  }
  async SetRule(arg0,arg1) {
    const args = newOAAuthorizationOperatorSetRuleArguments();
    args["expected_revision"] = arg0;
    args["rule"] = arg1;
    _serviceCheck("OAAuthorizationOperatorSetRuleArguments", args);
    const payload = _serviceEncode(enc_oaauthorizationoperatorsetrulearguments, args, 1);
    _serviceDecode(decode_oaauthorizationoperatorsetrulearguments, payload, 1);
    const request = _serviceRequest("abstraction.rights/operator@1", "SetRule", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.rights/operator@1", "SetRule");
    const result = _serviceDecode(decode_oaauthorizationoperatorsetruleresult, reply, 1);
    return result.value;
  }
  async RevokeRule(arg0,arg1,arg2,arg3) {
    const args = newOAAuthorizationOperatorRevokeRuleArguments();
    args["expected_revision"] = arg0;
    args["subject"] = arg1;
    args["action"] = arg2;
    args["resource"] = arg3;
    _serviceCheck("OAAuthorizationOperatorRevokeRuleArguments", args);
    const payload = _serviceEncode(enc_oaauthorizationoperatorrevokerulearguments, args, 1);
    _serviceDecode(decode_oaauthorizationoperatorrevokerulearguments, payload, 1);
    const request = _serviceRequest("abstraction.rights/operator@1", "RevokeRule", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.rights/operator@1", "RevokeRule");
    const result = _serviceDecode(decode_oaauthorizationoperatorrevokeruleresult, reply, 1);
    return result.value;
  }
}
export const AuthorizationOperatorService = Object.freeze({wireName:"abstraction.rights/operator@1",Client:AuthorizationOperatorClient});
