# Code generated by abstraction-idl from abstraction-rights/rights.thrift. DO NOT EDIT.

"""abstraction.rights.api: generated contract types, vocabularies and service clients."""

from ._codec import (
    ActionEdit,
    ActionEditOutcome,
    AppMetadata,
    Authorization,
    AuthorizationClient,
    AuthorizationOperator,
    AuthorizationOperatorClient,
    CatalogEntry,
    Decision,
    DecisionOutcome,
    DispatchError,
    HoldMetadata,
    KNOWN_RIGHTS,
    OPERATIONS,
    PolicyEdit,
    PolicyEditOutcome,
    PolicyPage,
    PolicyPageOutcome,
    PolicyRule,
    REFUSAL_CODES,
    RESOURCE_ACTIONS,
    Refusal,
    Request,
    ResponseMetadata,
    RuleRead,
    RuleReadOutcome,
    RuleRecord,
    ServiceError,
    ServiceErrorCode,
    Subject,
    decode,
    encode,
    service_name,
)

__all__ = [
    "ActionEdit",
    "ActionEditOutcome",
    "AppMetadata",
    "Authorization",
    "AuthorizationClient",
    "AuthorizationOperator",
    "AuthorizationOperatorClient",
    "CatalogEntry",
    "Decision",
    "DecisionOutcome",
    "DispatchError",
    "HoldMetadata",
    "KNOWN_RIGHTS",
    "OPERATIONS",
    "PolicyEdit",
    "PolicyEditOutcome",
    "PolicyPage",
    "PolicyPageOutcome",
    "PolicyRule",
    "REFUSAL_CODES",
    "RESOURCE_ACTIONS",
    "Refusal",
    "Request",
    "ResponseMetadata",
    "RuleRead",
    "RuleReadOutcome",
    "RuleRecord",
    "ServiceError",
    "ServiceErrorCode",
    "Subject",
    "decode",
    "encode",
    "service_name",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
